"""ilk şema

MASTER-SPEC §13 veri modeli. TimescaleDB hypertable'ı ve continuous aggregate'ler
tabloların ardından kurulur (§2.2).

Revision ID: 0001_ilk_sema
Revises:
Create Date: 2026-08-14
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import context, op

revision: str = "0001_ilk_sema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# 15m ham saklanır; üstü continuous aggregate ile türetilir (§2.2).
CONTINUOUS_AGGREGATES = (
    ("ohlcv_1h", "1 hour"),
    ("ohlcv_4h", "4 hours"),
    ("ohlcv_1d", "1 day"),
)


def _timescale_available() -> bool:
    """TimescaleDB kurulu mu?

    `--sql` (çevrimdışı) modda bağlantı yoktur; script bir DBA tarafından
    çalıştırılacağı için Timescale komutları koşulsuz yazılır.
    """
    if context.is_offline_mode():
        return True
    return bool(
        op.get_bind()
        .exec_driver_sql("SELECT 1 FROM pg_extension WHERE extname = 'timescaledb'")
        .scalar()
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "correlation_clusters",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("assignments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_correlation_clusters")),
    )
    op.create_table(
        "data_quality_reports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_reports")),
    )
    op.create_table(
        "ohlcv",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("high", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("low", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("close", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("volume", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("quote_volume", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("taker_buy_quote", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "timeframe", "open_time", name=op.f("pk_ohlcv")),
    )
    op.create_table(
        "patterns",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("neckline", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("target", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("volume_confirmed", sa.Boolean(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patterns")),
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("bar_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("families", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("modifiers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
        sa.UniqueConstraint("symbol", "bar_time", "timeframe", "config_hash", name="uq_score_bar"),
    )
    op.create_table(
        "spread_samples",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("spread_pct", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("sampled_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spread_samples")),
    )
    op.create_table(
        "sr_levels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("strength", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("touches", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sr_levels")),
    )
    op.create_table(
        "symbol_info",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("base_asset", sa.String(length=16), nullable=False),
        sa.Column("quote_asset", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("is_spot_allowed", sa.Boolean(), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("step_size", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("min_notional", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("listed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delist_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_symbol_info")),
    )
    op.create_table(
        "universe_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("symbols", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("funnel", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("added", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("removed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universe_snapshots")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("totp_secret", sa.Text(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "blacklist",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_blacklist_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_blacklist")),
    )
    op.create_table(
        "chat_rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_chat_rooms_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_rooms")),
    )
    op.create_table(
        "integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("config_encrypted", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_integrations_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("kind", name=op.f("uq_integrations_kind")),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_table(
        "score_observations",
        sa.Column("score_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("bar_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("families", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fwd_return_4h", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column("fwd_return_24h", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column("fwd_return_72h", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["scores.id"],
            name=op.f("fk_score_observations_score_id_scores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("score_id", name=op.f("pk_score_observations")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_settings_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_strategies_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
    )
    op.create_table(
        "chat_members",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
            name=op.f("fk_chat_members_room_id_chat_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chat_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("room_id", "user_id", name=op.f("pk_chat_members")),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
            name=op.f("fk_chat_messages_room_id_chat_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chat_messages_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("frozen", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_strategy_versions_strategy_id_strategies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_versions")),
        sa.UniqueConstraint("strategy_id", "version", name="uq_strategy_version"),
    )
    op.create_table(
        "backtests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_version_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("approximate_universe", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_backtests_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_backtests_strategy_version_id_strategy_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtests")),
    )
    op.create_table(
        "bots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("strategy_version_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("capital", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("equity_peak", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entries_blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("halt_reason", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_bots_owner_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_bots_strategy_version_id_strategy_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bots")),
    )
    op.create_table(
        "backtest_results",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("backtest_id", sa.Integer(), nullable=False),
        sa.Column("cost_scenario", sa.String(length=16), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("equity_curve", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trades", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("benchmarks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtests.id"],
            name=op.f("fk_backtest_results_backtest_id_backtests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_results")),
    )
    op.create_table(
        "bot_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_bot_events_bot_id_bots"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_events")),
    )
    op.create_table(
        "equity_points",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("exposure", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_equity_points_bot_id_bots"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equity_points")),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("entry_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stop", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("initial_stop", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("target", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("score_at_entry", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("rationale_id", sa.BigInteger(), nullable=True),
        sa.Column("breakeven_locked", sa.Boolean(), nullable=False),
        sa.Column("mfe", sa.Numeric(precision=14, scale=8), nullable=False),
        sa.Column("mae", sa.Numeric(precision=14, scale=8), nullable=False),
        sa.Column("entry_fees", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_positions_bot_id_bots"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rationale_id"],
            ["scores.id"],
            name=op.f("fk_positions_rationale_id_scores"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("filled_qty", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("avg_fill_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("exchange_order_id", sa.String(length=64), nullable=True),
        sa.Column("fees", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_orders_bot_id_bots"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_orders_position_id_positions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("exit_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_reason", sa.String(length=24), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("pnl_r", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("fees", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("mfe", sa.Numeric(precision=14, scale=8), nullable=False),
        sa.Column("mae", sa.Numeric(precision=14, scale=8), nullable=False),
        sa.Column("hold_hours", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_trades_bot_id_bots"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_trades_position_id_positions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
    )
    # ### end Alembic commands ###
    op.create_index(
        "ix_correlation_clusters_computed_at", "correlation_clusters", ["computed_at"], unique=False
    )
    op.create_index(
        "ix_data_quality_reports_created_at", "data_quality_reports", ["created_at"], unique=False
    )
    op.create_index("ix_data_quality_reports_kind", "data_quality_reports", ["kind"], unique=False)
    op.create_index(
        "ix_data_quality_reports_symbol", "data_quality_reports", ["symbol"], unique=False
    )
    op.create_index(
        "ix_ohlcv_symbol_tf_time", "ohlcv", ["symbol", "timeframe", "open_time"], unique=False
    )
    op.create_index("ix_patterns_detected_at", "patterns", ["detected_at"], unique=False)
    op.create_index("ix_patterns_symbol", "patterns", ["symbol"], unique=False)
    op.create_index("ix_scores_bar_time", "scores", ["bar_time"], unique=False)
    op.create_index("ix_scores_bartime_score", "scores", ["bar_time", "score"], unique=False)
    op.create_index("ix_scores_config_hash", "scores", ["config_hash"], unique=False)
    op.create_index("ix_scores_symbol", "scores", ["symbol"], unique=False)
    op.create_index("ix_spread_samples_sampled_at", "spread_samples", ["sampled_at"], unique=False)
    op.create_index("ix_spread_samples_symbol", "spread_samples", ["symbol"], unique=False)
    op.create_index("ix_sr_levels_computed_at", "sr_levels", ["computed_at"], unique=False)
    op.create_index("ix_sr_levels_symbol", "sr_levels", ["symbol"], unique=False)
    op.create_index(
        "ix_sr_symbol_tf_time", "sr_levels", ["symbol", "timeframe", "computed_at"], unique=False
    )
    op.create_index(
        "ix_universe_snapshots_config_hash", "universe_snapshots", ["config_hash"], unique=False
    )
    op.create_index(
        "ix_universe_snapshots_taken_at", "universe_snapshots", ["taken_at"], unique=False
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_audit_log_action", "audit_log", ["action"], unique=False)
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"], unique=False)
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"], unique=False)
    op.create_index("ix_notifications_kind", "notifications", ["kind"], unique=False)
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"], unique=False)
    op.create_index(
        "ix_score_observations_bar_time", "score_observations", ["bar_time"], unique=False
    )
    op.create_index("ix_score_observations_symbol", "score_observations", ["symbol"], unique=False)
    op.create_index("ix_sessions_token_hash", "sessions", ["token_hash"], unique=True)
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"], unique=False)
    op.create_index("ix_chat_messages_created_at", "chat_messages", ["created_at"], unique=False)
    op.create_index("ix_chat_messages_room_id", "chat_messages", ["room_id"], unique=False)
    op.create_index(
        "ix_strategy_versions_definition_hash",
        "strategy_versions",
        ["definition_hash"],
        unique=False,
    )
    op.create_index(
        "ix_strategy_versions_strategy_id", "strategy_versions", ["strategy_id"], unique=False
    )
    op.create_index("ix_backtests_status", "backtests", ["status"], unique=False)
    op.create_index("ix_bots_state", "bots", ["state"], unique=False)
    op.create_index(
        "ix_backtest_results_backtest_id", "backtest_results", ["backtest_id"], unique=False
    )
    op.create_index("ix_bot_events_bot_id", "bot_events", ["bot_id"], unique=False)
    op.create_index("ix_bot_events_created_at", "bot_events", ["created_at"], unique=False)
    op.create_index("ix_bot_events_kind", "bot_events", ["kind"], unique=False)
    op.create_index("ix_equity_points_at", "equity_points", ["at"], unique=False)
    op.create_index("ix_equity_points_bot_id", "equity_points", ["bot_id"], unique=False)
    op.create_index("ix_positions_bot_id", "positions", ["bot_id"], unique=False)
    op.create_index("ix_positions_entry_time", "positions", ["entry_time"], unique=False)
    op.create_index("ix_positions_status", "positions", ["status"], unique=False)
    op.create_index("ix_positions_symbol", "positions", ["symbol"], unique=False)
    op.create_index("ix_orders_bot_id", "orders", ["bot_id"], unique=False)
    op.create_index("ix_orders_created_at", "orders", ["created_at"], unique=False)
    op.create_index("ix_orders_status", "orders", ["status"], unique=False)
    op.create_index("ix_orders_symbol", "orders", ["symbol"], unique=False)
    op.create_index("ix_trades_bot_id", "trades", ["bot_id"], unique=False)
    op.create_index("ix_trades_exit_reason", "trades", ["exit_reason"], unique=False)
    op.create_index("ix_trades_exit_time", "trades", ["exit_time"], unique=False)
    op.create_index("ix_trades_position_id", "trades", ["position_id"], unique=False)
    op.create_index("ix_trades_symbol", "trades", ["symbol"], unique=False)

    # --- TimescaleDB ---------------------------------------------------- #
    # Eklenti yoksa migrasyon yine de geçerli: ohlcv düz tablo olarak kalır.
    # Bu, geliştiricinin düz PostgreSQL ile de çalışabilmesi içindir.
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE")

    if not _timescale_available():
        return

    op.execute(
        "SELECT create_hypertable('ohlcv', 'open_time', "
        "chunk_time_interval => INTERVAL '7 days', migrate_data => TRUE)"
    )

    for name, bucket in CONTINUOUS_AGGREGATES:
        op.execute(
            f"""
            CREATE MATERIALIZED VIEW IF NOT EXISTS {name}
            WITH (timescaledb.continuous) AS
            SELECT
                symbol,
                time_bucket(INTERVAL '{bucket}', open_time) AS open_time,
                first(open, open_time)  AS open,
                max(high)               AS high,
                min(low)                AS low,
                last(close, open_time)  AS close,
                sum(volume)             AS volume,
                sum(quote_volume)       AS quote_volume,
                sum(trades)             AS trades,
                sum(taker_buy_base)     AS taker_buy_base,
                sum(taker_buy_quote)    AS taker_buy_quote
            FROM ohlcv
            WHERE timeframe = '15m'
            GROUP BY symbol, 2
            WITH NO DATA
            """
        )


def downgrade() -> None:

    if _timescale_available():
        for name, _ in reversed(CONTINUOUS_AGGREGATES):
            op.execute(f"DROP MATERIALIZED VIEW IF EXISTS {name}")

    op.drop_index("ix_trades_symbol", table_name="trades")
    op.drop_index("ix_trades_position_id", table_name="trades")
    op.drop_index("ix_trades_exit_time", table_name="trades")
    op.drop_index("ix_trades_exit_reason", table_name="trades")
    op.drop_index("ix_trades_bot_id", table_name="trades")
    op.drop_index("ix_orders_symbol", table_name="orders")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_created_at", table_name="orders")
    op.drop_index("ix_orders_bot_id", table_name="orders")
    op.drop_index("ix_positions_symbol", table_name="positions")
    op.drop_index("ix_positions_status", table_name="positions")
    op.drop_index("ix_positions_entry_time", table_name="positions")
    op.drop_index("ix_positions_bot_id", table_name="positions")
    op.drop_index("ix_equity_points_bot_id", table_name="equity_points")
    op.drop_index("ix_equity_points_at", table_name="equity_points")
    op.drop_index("ix_bot_events_kind", table_name="bot_events")
    op.drop_index("ix_bot_events_created_at", table_name="bot_events")
    op.drop_index("ix_bot_events_bot_id", table_name="bot_events")
    op.drop_index("ix_backtest_results_backtest_id", table_name="backtest_results")
    op.drop_index("ix_bots_state", table_name="bots")
    op.drop_index("ix_backtests_status", table_name="backtests")
    op.drop_index("ix_strategy_versions_strategy_id", table_name="strategy_versions")
    op.drop_index("ix_strategy_versions_definition_hash", table_name="strategy_versions")
    op.drop_index("ix_chat_messages_room_id", table_name="chat_messages")
    op.drop_index("ix_chat_messages_created_at", table_name="chat_messages")
    op.drop_index("ix_sessions_user_id", table_name="sessions")
    op.drop_index("ix_sessions_token_hash", table_name="sessions")
    op.drop_index("ix_score_observations_symbol", table_name="score_observations")
    op.drop_index("ix_score_observations_bar_time", table_name="score_observations")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_index("ix_notifications_kind", table_name="notifications")
    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.drop_index("ix_audit_log_created_at", table_name="audit_log")
    op.drop_index("ix_audit_log_action", table_name="audit_log")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_universe_snapshots_taken_at", table_name="universe_snapshots")
    op.drop_index("ix_universe_snapshots_config_hash", table_name="universe_snapshots")
    op.drop_index("ix_sr_symbol_tf_time", table_name="sr_levels")
    op.drop_index("ix_sr_levels_symbol", table_name="sr_levels")
    op.drop_index("ix_sr_levels_computed_at", table_name="sr_levels")
    op.drop_index("ix_spread_samples_symbol", table_name="spread_samples")
    op.drop_index("ix_spread_samples_sampled_at", table_name="spread_samples")
    op.drop_index("ix_scores_symbol", table_name="scores")
    op.drop_index("ix_scores_config_hash", table_name="scores")
    op.drop_index("ix_scores_bartime_score", table_name="scores")
    op.drop_index("ix_scores_bar_time", table_name="scores")
    op.drop_index("ix_patterns_symbol", table_name="patterns")
    op.drop_index("ix_patterns_detected_at", table_name="patterns")
    op.drop_index("ix_ohlcv_symbol_tf_time", table_name="ohlcv")
    op.drop_index("ix_data_quality_reports_symbol", table_name="data_quality_reports")
    op.drop_index("ix_data_quality_reports_kind", table_name="data_quality_reports")
    op.drop_index("ix_data_quality_reports_created_at", table_name="data_quality_reports")
    op.drop_index("ix_correlation_clusters_computed_at", table_name="correlation_clusters")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trades")
    op.drop_table("orders")
    op.drop_table("positions")
    op.drop_table("equity_points")
    op.drop_table("bot_events")
    op.drop_table("backtest_results")
    op.drop_table("bots")
    op.drop_table("backtests")
    op.drop_table("strategy_versions")
    op.drop_table("chat_messages")
    op.drop_table("chat_members")
    op.drop_table("strategies")
    op.drop_table("settings")
    op.drop_table("sessions")
    op.drop_table("score_observations")
    op.drop_table("notifications")
    op.drop_table("integrations")
    op.drop_table("chat_rooms")
    op.drop_table("blacklist")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("universe_snapshots")
    op.drop_table("symbol_info")
    op.drop_table("sr_levels")
    op.drop_table("spread_samples")
    op.drop_table("scores")
    op.drop_table("patterns")
    op.drop_table("ohlcv")
    op.drop_table("data_quality_reports")
    op.drop_table("correlation_clusters")
    # ### end Alembic commands ###
